name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [28, 29, 30]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v2
      with:
        api-level: ${{ matrix.api-level }}
        build-tools: 30.0.3

    - name: Install system image
      run: sdkmanager "system-images;android-${{ matrix.api-level }};google_apis;x86_64"

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create AVD
      run: echo "no" | avdmanager create avd -n test -k "system-images;android-${{ matrix.api-level }};google_apis;x86_64" --device "pixel"

    - name: Start AVD
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -accel off -gpu swiftshader_indirect -no-snapshot &
        adb wait-for-device

    - name: Wait for emulator to boot
      run: |
        boot_completed=""
        retries=0
        while [[ -z "$boot_completed" && $retries -lt 600 ]]; do
          echo "Waiting for emulator to boot..."
          boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
          sleep 1
          retries=$((retries + 1))
        done
        if [[ -z "$boot_completed" ]]; then
          echo "Emulator failed to boot"
          adb shell logcat -d
          exit 1
        fi
        echo "Emulator booted successfully"
        adb shell input keyevent 82

    - name: Run instrumented tests
      run: ./gradlew connectedAndroidTest

    - name: Run unit tests
      run: ./gradlew test

    - name: Run lint
      run: ./gradlew lint
