name: Android Emulator Boot Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  emulator-boot:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3.2.1
      with:
        api-level: 29
        build-tools: 29.0.3

    - name: Install system image
      run: sdkmanager "system-images;android-30;google_apis;x86_64"

    - name: Create AVD
      run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "Nexus 5"

    - name: Start AVD
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -accel off -gpu swiftshader_indirect -no-snapshot -verbose &
        adb wait-for-device

    - name: Wait for emulator to boot
      run: |
        boot_completed=""
        retries=0
        timeout=1200  # Increase the timeout to 20 minutes
        while [[ -z "$boot_completed" && $retries -lt $timeout ]]; do
          echo "Waiting for emulator to boot..."
          boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
          sleep 1
          retries=$((retries + 1))
        done
        if [[ "$boot_completed" != "1" ]]; then
          echo "Emulator failed to boot within $timeout seconds"
          adb shell logcat -d > emulator_logcat.txt
          adb shell dumpsys meminfo > emulator_meminfo.txt
          adb shell dumpsys cpuinfo > emulator_cpuinfo.txt
          exit 1
        fi
        echo "Emulator booted successfully"
        adb shell input keyevent 82

    - name: Get emulator status
      run: adb shell getprop

    - name: Validate Device API Level
      run: |
        api_level=$(adb shell getprop ro.build.version.sdk)
        echo "Device API Level: $api_level"
        if [[ "$api_level" != "30" ]]; then
          echo "Emulator API Level mismatch, expected 30 but got $api_level"
          adb shell logcat -d > emulator_logcat.txt
          exit 1
        fi

    - name: Upload emulator logcat
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: emulator-logcat
        path: emulator_logcat.txt

    - name: Upload emulator meminfo
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: emulator-meminfo
        path: emulator_meminfo.txt

    - name: Upload emulator cpuinfo
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: emulator-cpuinfo
        path: emulator_cpuinfo.txt