name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Android SDK
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -O commandlinetools-linux.zip
        unzip commandlinetools-linux.zip -d $ANDROID_HOME/cmdline-tools
        mv $ANDROID_HOME/cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-29" "build-tools;29.0.3" "system-images;android-29;google_apis;x86_64" "emulator"

    - name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build

    - name: Create AVD
      run: echo "no" | $ANDROID_HOME/cmdline-tools/latest/bin/avdmanager create avd -n test -k "system-images;android-29;google_apis;x86_64" --device "Nexus 5"

    - name: Start AVD
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-window -no-audio -no-boot-anim -accel off -gpu swiftshader_indirect -verbose &
        adb wait-for-device

    - name: Wait for emulator to boot
      run: |
        boot_completed=""
        retries=0
        timeout=1200  # Increase the timeout to 20 minutes
        while [[ -z "$boot_completed" && $retries -lt $timeout ]]; do
          echo "Waiting for emulator to boot..."
          boot_completed=$(adb shell getprop sys.boot_completed 2>/dev/null | tr -d '\r')
          sleep 1
          retries=$((retries + 1))
        done
        if [[ -z "$boot_completed" ]]; then
          echo "Emulator failed to boot within $timeout seconds"
          adb shell logcat -d > emulator_logcat.txt
          exit 1
        fi
        echo "Emulator booted successfully"
        adb shell input keyevent 82

    - name: Get emulator status
      run: adb shell getprop

    - name: Upload emulator logcat
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: emulator-logcat
        path: emulator_logcat.txt

    - name: Run instrumented tests
      run: ./gradlew connectedAndroidTest

    - name: Run unit tests
      run: ./gradlew test

    - name: Run lint
      run: ./gradlew lint
