name: Android CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v4.2.1
      with:
        distribution: 'adopt'
        java-version: '17'

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3.2.1
      with:
        api-level: 30
        build-tools: 30.0.3

    - name: Install system image
      run: sdkmanager "system-images;android-30;google_apis;x86_64"

    - name: Cache Gradle packages
      uses: actions/cache@v4.0.2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Create AVD
      run: echo "no" | avdmanager create avd -n test -k "system-images;android-30;google_apis;x86_64" --device "Nexus 5"

    - name: Start AVD
      run: |
        $ANDROID_HOME/emulator/emulator -avd test -no-audio -no-window -accel off -gpu swiftshader_indirect -no-snapshot -verbose &
        adb wait-for-device

    - name: Build with Gradle
      run: ./gradlew build

    - name: Validate Device API Level
      run: |
        api_level=$(adb shell getprop ro.build.version.sdk)
        echo "Device API Level: $api_level"
        if [[ "$api_level" != "30" ]]; then
          echo "Emulator API Level mismatch, expected 30 but got $api_level"
          adb shell logcat -d > emulator_logcat.txt
          exit 1
        fi

    - name: Upload emulator logcat
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: emulator-logcat
        path: emulator_logcat.txt

    - name: Upload emulator meminfo
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: emulator-meminfo
        path: emulator_meminfo.txt

    - name: Upload emulator cpuinfo
      if: failure()
      uses: actions/upload-artifact@v2
      with:
        name: emulator-cpuinfo
        path: emulator_cpuinfo.txt

    - name: Run instrumented tests
      run: ./gradlew connectedAndroidTest --info

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: android-test-results
        path: app/build/reports/androidTests/connected/